lst=["jan","feb","mar","apr","may"]
print(lst)
lst.append("dec")
lst.append("dec")
print(lst.count("dec"))

lst.append("june")
print(lst)
lst.insert(6, "july")
print(lst)
lst.insert(7, "aug")
print(lst)
lst.pop()
print(lst)
lst.pop(3)
print(lst)
lst.remove("jan")
print(lst)
print(lst.index("july"))
lst.reverse()
print(lst)
