percentages=(99,95,90,89,93,96)
print(percentages)
print(percentages[1])
print(percentages[2:5])
print(percentages[:4])
del percentages
my_tuple=(1,2,3,4,5,6)
print(my_tuple)
print (len(my_tuple))
print(max(my_tuple))
print(sum(my_tuple))
print(my_tuple.index(6))